/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(statistics.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(0903d9f7ad663508fd76ef4aefe7ffb6)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/pulsed_power/statistics.h>
// pydoc.h is automatically generated in the build directory
#include <statistics_pydoc.h>

void bind_statistics(py::module& m)
{

    using statistics    = gr::pulsed_power::statistics;


    py::class_<statistics, gr::block, gr::basic_block,
        std::shared_ptr<statistics>>(m, "statistics", D(statistics))

        .def(py::init(&statistics::make),
           D(statistics,make)
        )
        



        ;




}








