/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-pulsed_power
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_PULSED_POWER_API_H
#define INCLUDED_PULSED_POWER_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_pulsed_power_EXPORTS
#define PULSED_POWER_API __GR_ATTR_EXPORT
#else
#define PULSED_POWER_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_PULSED_POWER_API_H */
