# This is a basic workflow to help you get started with Actions

name: ci_visualization

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  SRC_DIR: "src/implot_visualization"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install emscripten
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: 2.0.14
          # actions-cache-folder: "emsdk-cache"

      - name: Verify emscripten
        run: emcc -v

      - name: Generate
        run: emcmake cmake -S ${{env.SRC_DIR}} -B ${{env.SRC_DIR}}/build

      - name: Build
        run: cd ${{env.SRC_DIR}}/build && emmake make
