name: ci_worker

on:
  push:
    branches: "*"
  pull_request:
    branches: [main]
  release:
    types: [created]

env:
  REFERENCE_CONFIG: "Ubuntu Latest gcc" # configuration used for coverage etc
  SRC_DIR_GR: "src/gr-pulsed_power"
  SRC_DIR_WORKER: "src/opencmw_worker"

jobs:
  build:
    name: "${{ matrix.configurations.name }} | ${{ matrix.cmake-build-type }}"
    environment: configure coverage
    runs-on: ${{ matrix.configurations.os }}
    strategy:
      fail-fast: false
      matrix:
        configurations:
          - name: Ubuntu Latest gcc
            os: ubuntu-latest
            compiler: gcc
          - name: Ubuntu Latest clang
            os: ubuntu-latest
            compiler: clang
          # - name: MacOS Latest # deactivated because mp-units is not compatible with clangApple
          #   os: macos-latest
          # - name: Windows Latest # deactivated because msvc fails because of clang pragmas
          #   os: windows-latest
        # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
        cmake-build-type: [Release, Debug]

    steps:
      - uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        env:
          cache-name: cache-fetchContent-cache
        with:
          path: ${{runner.workspace}}/build/_deps
          key: ${{ runner.os }}-${{ matrix.configurations.compiler }}-${{ matrix.cmake-build-type }}-${{ hashFiles('CMakeLists.txt') }}-${{ hashFiles('cmake/Dependencies.cmake') }}

      - name: Install gcc-11
        if: matrix.configurations.compiler == 'gcc'
        run: |
          sudo apt-get install -y gcc-11 g++-11
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 110 --slave /usr/bin/g++ g++ /usr/bin/g++-11 --slave /usr/bin/gcov gcov /usr/bin/gcov-11

      - name: Configure GNU Radio pulsed-power out of tree module
        shell: bash
        run: cmake -S ${{env.SRC_DIR_GR}} -B ${{env.SRC_DIR_GR}}/build

      - name: Build GNU Radio pulsed-power out of tree module
        shell: bash
        run: cmake --build ${{env.SRC_DIR_GR}}/build --target install && ldconfig

      - name: Configure CMake
        # Use a bash shell, so we can use the same syntax for environment variable access regardless of the host operating system
        shell: bash
        run: cmake -S ${{env.SRC_DIR_WORKER}} -B ${{env.SRC_DIR_WORKER}}/build -DCMAKE_BUILD_TYPE=${{ matrix.cmake-build-type }}

      - name: Build worker
        shell: bash
        # Execute the build.  You can specify a specific target with "--target <NAME>"
        run: cmake --build ${{env.SRC_DIR_WORKER}}/build

      - name: Run tests
        if: matrix.configurations.name != env.REFERENCE_CONFIG || matrix.cmake-build-type != 'Debug'
        working-directory: ${{env.SRC_DIR_WORKER}}/build
        shell: bash
        # Execute tests defined by the CMake configuration. The coverage target runs the autodiscovered catch2 tests using
        # ctest and records the coverage using gcov
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest -C ${{ matrix.cmake-build-type }}
